<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(ProjectDir)..\.props" />

  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <Configurations>Debug;Release</Configurations>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>13</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\BasisNetworkCore\BasisNetworkCore.csproj" />
  </ItemGroup>
</Project>
