using System;
using System.IO;
using Unity.Collections;
using UnityEngine;

/// <summary>
/// Versioned binary payload describing a distance far avatar for one avatar: a collapsed
/// humanoid skeleton snapshot, a quantized low-poly skinned mesh, and pre-compressed
/// texture payloads. Generated by the SDK at bundle build time and carried in
/// <see cref="BasisBundleConnector.FarLodBase64"/>, so it is available from a
/// connector-only download without loading the AssetBundle.
///
/// The payload arrives over the network (inside the bee connector), so parsing is
/// defensive: hard caps on every count, and any violation aborts the parse.
///
/// Skeleton convention: bones are humanoid bones only, parented to their nearest humanoid
/// ancestor. Rest local TRS is composed through any non-humanoid intermediate transforms at
/// T-pose, which keeps `restLocalRotation * networkDelta` world-equivalent to the original
/// hierarchy (intermediates are static on remotes). Rest rotations double as the TposeLocal
/// array for RemoteBoneJobSystem registration.
/// </summary>
public class BasisFarLodPayload
{
    public const uint MagicValue = 0x444C4642; // "BFLD" little-endian
    // v2: adds the measured lighting response clamps (MinBrightness/MaxBrightness).
    public const ushort CurrentVersion = 3;
    /// <summary>
    /// Oldest payload version this build parses. v1/v2 blobs only existed during development
    /// and their layout drifted WITHOUT version bumps, so they can misparse into plausible
    /// garbage (observed as a ~7km mouth offset lever); they are refused outright. Any future
    /// layout change MUST bump <see cref="CurrentVersion"/> — the end marker + exact-length
    /// check in TryParse then turns a writer/reader mismatch into a rejection, never garbage.
    /// </summary>
    public const ushort MinSupportedVersion = 3;

    public const int MaxBones = 64;
    public const int MaxVertices = 16384;
    public const int MaxIndexCount = 98304;
    public const int MaxTextureDimension = 2048;
    public const int MaxTexturePayloadBytes = 6 * 1024 * 1024;
    public const int MaxTextures = 4;
    public const int MaxPayloadBytes = 16 * 1024 * 1024;

    public enum FarLodTextureFormat : byte
    {
        BC1 = 0,
        ASTC6x6 = 1,
        RGBA32 = 2,
    }

    [Serializable]
    public struct FarLodTexture
    {
        public FarLodTextureFormat Format;
        public ushort Width;
        public ushort Height;
        public byte MipCount;
        public byte[] Data;
    }

    // Skeleton (collapsed humanoid). Parallel arrays, index = bone index.
    public byte[] BoneHumanBodyBone;
    public byte[] BoneParentIndex; // 0xFF = root bone (hips)
    public Vector3[] BoneRestLocalPosition;
    public Quaternion[] BoneRestLocalRotation;

    // Measured lighting response of the avatar's own shaders (bake-time capture probe):
    // toon shaders clamp their light term between a floor and a cap, and matching that is
    // what keeps the far avatar from going pitch black or blowing out where the real avatar
    // wouldn't. Min 0 / Max 4 ≈ an unclamped standard-lit response.
    public float MinBrightness;
    public float MaxBrightness = 4f;

    // Registration anchors, mirroring what BasisRemoteAvatarDriver passes to AddRemotePlayer.
    public Vector2 AvatarEyePosition;
    public Vector2 AvatarMouthPosition;
    public Vector3 AuthoredRootScale = Vector3.one;
    public Vector3 TposeHeadFromRootPosition;
    public Quaternion TposeHeadFromRootRotation = Quaternion.identity;
    public Vector3 TposeHipsFromRootPosition;
    public Quaternion TposeHipsFromRootRotation = Quaternion.identity;

    // Mesh. Positions quantized to 16 bits per axis inside [PositionBoundsMin, PositionBoundsMax]
    // (animator-root space at T-pose). LocalBounds* is the renderer's localBounds in hips space.
    public Vector3 PositionBoundsMin;
    public Vector3 PositionBoundsMax;
    public Vector3 LocalBoundsCenter;
    public Vector3 LocalBoundsExtents;
    public int VertexCount;
    public ushort[] PositionsQ;  // 3 per vertex
    public ushort[] NormalsOct;  // 1 per vertex, 8+8 bit octahedral
    public ushort[] UvQ;         // 2 per vertex
    public byte[] BoneIndexA;    // 1 per vertex
    public byte[] BoneIndexB;    // 1 per vertex
    public byte[] BoneWeightA;   // 1 per vertex; weightB = 255 - weightA
    public ushort[] Indices;
    public FarLodTexture[] Textures = Array.Empty<FarLodTexture>();

    public int BoneCount => BoneHumanBodyBone?.Length ?? 0;
    public int TriangleCount => (Indices?.Length ?? 0) / 3;

    public byte[] Serialize()
    {
        using MemoryStream stream = new MemoryStream(256 * 1024);
        using BinaryWriter writer = new BinaryWriter(stream);

        writer.Write(MagicValue);
        writer.Write(CurrentVersion);
        writer.Write((ushort)0); // flags, reserved

        int boneCount = BoneCount;
        writer.Write((byte)boneCount);
        for (int i = 0; i < boneCount; i++)
        {
            writer.Write(BoneHumanBodyBone[i]);
            writer.Write(BoneParentIndex[i]);
            WriteVector3(writer, BoneRestLocalPosition[i]);
            WriteQuaternion(writer, BoneRestLocalRotation[i]);
        }

        writer.Write(MinBrightness);
        writer.Write(MaxBrightness);

        WriteVector2(writer, AvatarEyePosition);
        WriteVector2(writer, AvatarMouthPosition);
        WriteVector3(writer, AuthoredRootScale);
        WriteVector3(writer, TposeHeadFromRootPosition);
        WriteQuaternion(writer, TposeHeadFromRootRotation);
        WriteVector3(writer, TposeHipsFromRootPosition);
        WriteQuaternion(writer, TposeHipsFromRootRotation);

        WriteVector3(writer, PositionBoundsMin);
        WriteVector3(writer, PositionBoundsMax);
        WriteVector3(writer, LocalBoundsCenter);
        WriteVector3(writer, LocalBoundsExtents);

        writer.Write((ushort)VertexCount);
        for (int i = 0; i < VertexCount * 3; i++)
        {
            writer.Write(PositionsQ[i]);
        }
        for (int i = 0; i < VertexCount; i++)
        {
            writer.Write(NormalsOct[i]);
        }
        for (int i = 0; i < VertexCount * 2; i++)
        {
            writer.Write(UvQ[i]);
        }
        writer.Write(BoneIndexA, 0, VertexCount);
        writer.Write(BoneIndexB, 0, VertexCount);
        writer.Write(BoneWeightA, 0, VertexCount);

        writer.Write(Indices.Length);
        for (int i = 0; i < Indices.Length; i++)
        {
            writer.Write(Indices[i]);
        }

        int textureCount = Textures?.Length ?? 0;
        writer.Write((byte)textureCount);
        for (int i = 0; i < textureCount; i++)
        {
            writer.Write((byte)Textures[i].Format);
            writer.Write(Textures[i].Width);
            writer.Write(Textures[i].Height);
            writer.Write(Textures[i].MipCount);
            writer.Write(Textures[i].Data.Length);
            writer.Write(Textures[i].Data, 0, Textures[i].Data.Length);
        }

        // End marker: TryParse requires this magic at the exact final offset, so a blob
        // written by a mismatched layout rejects instead of misparsing into garbage fields.
        writer.Write(MagicValue);

        writer.Flush();
        return stream.ToArray();
    }

    public string SerializeToBase64()
    {
        return Convert.ToBase64String(Serialize());
    }

    public static BasisFarLodPayload TryParseBase64(string base64)
    {
        if (string.IsNullOrEmpty(base64))
        {
            return null;
        }
        byte[] bytes;
        try
        {
            bytes = Convert.FromBase64String(base64);
        }
        catch (FormatException)
        {
            BasisDebug.LogError("Far avatar payload was not valid base64", BasisDebug.LogTag.Avatar);
            return null;
        }
        return TryParse(bytes);
    }

    public static BasisFarLodPayload TryParse(byte[] bytes)
    {
        if (bytes == null || bytes.Length < 16 || bytes.Length > MaxPayloadBytes)
        {
            return null;
        }
        try
        {
            using MemoryStream stream = new MemoryStream(bytes, false);
            using BinaryReader reader = new BinaryReader(stream);

            if (reader.ReadUInt32() != MagicValue)
            {
                return null;
            }
            ushort version = reader.ReadUInt16();
            if (version < MinSupportedVersion || version > CurrentVersion)
            {
                BasisDebug.LogError($"Far avatar payload version {version} unsupported (this build reads {MinSupportedVersion}..{CurrentVersion}) — the avatar needs a rebuild with the current SDK", BasisDebug.LogTag.Avatar);
                return null;
            }
            reader.ReadUInt16(); // flags

            BasisFarLodPayload payload = new BasisFarLodPayload();

            int boneCount = reader.ReadByte();
            if (boneCount == 0 || boneCount > MaxBones)
            {
                return null;
            }
            payload.BoneHumanBodyBone = new byte[boneCount];
            payload.BoneParentIndex = new byte[boneCount];
            payload.BoneRestLocalPosition = new Vector3[boneCount];
            payload.BoneRestLocalRotation = new Quaternion[boneCount];
            for (int i = 0; i < boneCount; i++)
            {
                payload.BoneHumanBodyBone[i] = reader.ReadByte();
                payload.BoneParentIndex[i] = reader.ReadByte();
                payload.BoneRestLocalPosition[i] = ReadVector3(reader);
                payload.BoneRestLocalRotation[i] = ReadQuaternion(reader);
                if (payload.BoneHumanBodyBone[i] >= (byte)HumanBodyBones.LastBone)
                {
                    return null;
                }
                if (!IsSanePosition(payload.BoneRestLocalPosition[i], MaxAuthoredPositionMeters) ||
                    !IsSaneRotation(payload.BoneRestLocalRotation[i]))
                {
                    return null;
                }
                if (payload.BoneParentIndex[i] != 0xFF && payload.BoneParentIndex[i] >= i)
                {
                    // Parents must precede children so the runtime can build in one pass.
                    return null;
                }
            }

            payload.MinBrightness = Mathf.Clamp(reader.ReadSingle(), 0f, 1f);
            payload.MaxBrightness = Mathf.Clamp(reader.ReadSingle(), 0.5f, 8f);

            payload.AvatarEyePosition = ReadVector2(reader);
            payload.AvatarMouthPosition = ReadVector2(reader);
            payload.AuthoredRootScale = ReadVector3(reader);
            payload.TposeHeadFromRootPosition = ReadVector3(reader);
            payload.TposeHeadFromRootRotation = ReadQuaternion(reader);
            payload.TposeHipsFromRootPosition = ReadVector3(reader);
            payload.TposeHipsFromRootRotation = ReadQuaternion(reader);

            payload.PositionBoundsMin = ReadVector3(reader);
            payload.PositionBoundsMax = ReadVector3(reader);
            payload.LocalBoundsCenter = ReadVector3(reader);
            payload.LocalBoundsExtents = ReadVector3(reader);

            // Authored-space sanity. A stale/corrupt bake (e.g. a bee written by an interim
            // payload layout) can pass the structural checks yet parse into garbage floats
            // here — and these values feed the bone-job mouth/eye offsets, where one bad
            // float becomes a kilometers-long lever arm that pins every distance consumer
            // (ranges, voice, nameplates, far LOD swap-back) far away. Reject instead.
            if (!IsSaneVector2(payload.AvatarEyePosition, MaxAuthoredPositionMeters) ||
                !IsSaneVector2(payload.AvatarMouthPosition, MaxAuthoredPositionMeters) ||
                !IsSanePosition(payload.TposeHeadFromRootPosition, MaxAuthoredPositionMeters) ||
                !IsSanePosition(payload.TposeHipsFromRootPosition, MaxAuthoredPositionMeters) ||
                !IsSaneRotation(payload.TposeHeadFromRootRotation) ||
                !IsSaneRotation(payload.TposeHipsFromRootRotation) ||
                !IsSanePosition(payload.PositionBoundsMin, MaxAuthoredPositionMeters) ||
                !IsSanePosition(payload.PositionBoundsMax, MaxAuthoredPositionMeters) ||
                !IsSanePosition(payload.LocalBoundsCenter, MaxAuthoredPositionMeters) ||
                !IsSanePosition(payload.LocalBoundsExtents, MaxAuthoredPositionMeters) ||
                !IsSaneScale(payload.AuthoredRootScale))
            {
                return null;
            }

            int vertexCount = reader.ReadUInt16();
            if (vertexCount == 0 || vertexCount > MaxVertices)
            {
                return null;
            }
            payload.VertexCount = vertexCount;
            payload.PositionsQ = ReadUInt16Array(reader, vertexCount * 3);
            payload.NormalsOct = ReadUInt16Array(reader, vertexCount);
            payload.UvQ = ReadUInt16Array(reader, vertexCount * 2);
            payload.BoneIndexA = reader.ReadBytes(vertexCount);
            payload.BoneIndexB = reader.ReadBytes(vertexCount);
            payload.BoneWeightA = reader.ReadBytes(vertexCount);
            if (payload.BoneIndexA.Length != vertexCount || payload.BoneIndexB.Length != vertexCount || payload.BoneWeightA.Length != vertexCount)
            {
                return null;
            }
            for (int i = 0; i < vertexCount; i++)
            {
                if (payload.BoneIndexA[i] >= boneCount || payload.BoneIndexB[i] >= boneCount)
                {
                    return null;
                }
            }

            int indexCount = reader.ReadInt32();
            if (indexCount <= 0 || indexCount > MaxIndexCount || indexCount % 3 != 0)
            {
                return null;
            }
            payload.Indices = ReadUInt16Array(reader, indexCount);
            for (int i = 0; i < indexCount; i++)
            {
                if (payload.Indices[i] >= vertexCount)
                {
                    return null;
                }
            }

            int textureCount = reader.ReadByte();
            if (textureCount > MaxTextures)
            {
                return null;
            }
            payload.Textures = new FarLodTexture[textureCount];
            for (int i = 0; i < textureCount; i++)
            {
                FarLodTexture texture = new FarLodTexture
                {
                    Format = (FarLodTextureFormat)reader.ReadByte(),
                    Width = reader.ReadUInt16(),
                    Height = reader.ReadUInt16(),
                    MipCount = reader.ReadByte(),
                };
                int dataLength = reader.ReadInt32();
                if (texture.Width == 0 || texture.Height == 0 ||
                    texture.Width > MaxTextureDimension || texture.Height > MaxTextureDimension ||
                    dataLength <= 0 || dataLength > MaxTexturePayloadBytes)
                {
                    return null;
                }
                texture.Data = reader.ReadBytes(dataLength);
                if (texture.Data.Length != dataLength)
                {
                    return null;
                }
                payload.Textures[i] = texture;
            }

            // Integrity tail: the end marker must sit at the exact end of the blob. Any
            // writer/reader layout mismatch shifts it, so a stale or diverged bake is
            // refused here instead of surviving as shifted garbage fields.
            if (reader.ReadUInt32() != MagicValue || stream.Position != bytes.Length)
            {
                return null;
            }

            return payload;
        }
        catch (Exception e)
        {
            BasisDebug.LogError($"Far avatar payload parse failed: {e.Message}", BasisDebug.LogTag.Avatar);
            return null;
        }
    }

    /// <summary>Upper bound for any authored-space position component — generous even for giant avatars.</summary>
    private const float MaxAuthoredPositionMeters = 25f;

    private static bool IsSanePosition(Vector3 v, float limit)
    {
        return float.IsFinite(v.x) && float.IsFinite(v.y) && float.IsFinite(v.z) &&
               Mathf.Abs(v.x) <= limit && Mathf.Abs(v.y) <= limit && Mathf.Abs(v.z) <= limit;
    }

    private static bool IsSaneVector2(Vector2 v, float limit)
    {
        return float.IsFinite(v.x) && float.IsFinite(v.y) &&
               Mathf.Abs(v.x) <= limit && Mathf.Abs(v.y) <= limit;
    }

    private static bool IsSaneRotation(Quaternion q)
    {
        if (!float.IsFinite(q.x) || !float.IsFinite(q.y) || !float.IsFinite(q.z) || !float.IsFinite(q.w))
        {
            return false;
        }
        float magSq = q.x * q.x + q.y * q.y + q.z * q.z + q.w * q.w;
        return magSq > 0.5f && magSq < 2f;
    }

    private static bool IsSaneScale(Vector3 s)
    {
        return float.IsFinite(s.x) && float.IsFinite(s.y) && float.IsFinite(s.z) &&
               s.x > 1e-4f && s.y > 1e-4f && s.z > 1e-4f &&
               s.x <= 1000f && s.y <= 1000f && s.z <= 1000f;
    }

    public int FindBone(HumanBodyBones bone)
    {
        byte value = (byte)bone;
        for (int i = 0; i < BoneCount; i++)
        {
            if (BoneHumanBodyBone[i] == value)
            {
                return i;
            }
        }
        return -1;
    }

    /// <summary>
    /// Rest pose of every bone in animator-root space, composed down the collapsed hierarchy.
    /// Used for bind poses; runtime bone scale is unity (network scale applies at the root).
    /// </summary>
    public void ComputeBoneRootSpace(out Vector3[] positions, out Quaternion[] rotations)
    {
        int boneCount = BoneCount;
        positions = new Vector3[boneCount];
        rotations = new Quaternion[boneCount];
        for (int i = 0; i < boneCount; i++)
        {
            byte parent = BoneParentIndex[i];
            if (parent == 0xFF)
            {
                positions[i] = BoneRestLocalPosition[i];
                rotations[i] = BoneRestLocalRotation[i];
            }
            else
            {
                positions[i] = positions[parent] + rotations[parent] * BoneRestLocalPosition[i];
                rotations[i] = rotations[parent] * BoneRestLocalRotation[i];
            }
        }
    }

    /// <summary>
    /// Quantized mesh data decoded to engine-ready arrays. Every field is plain managed data,
    /// so the whole decode can run on a worker thread; the main thread only pays for the
    /// engine-side copies and the GPU upload in <see cref="CreateMesh"/>.
    /// </summary>
    public sealed class DecodedMeshData
    {
        public Vector3[] Vertices;
        public Vector3[] Normals;
        public Vector2[] Uv;
        public int[] Triangles;
        public byte[] BonesPerVertex;
        public BoneWeight1[] BoneWeights;
        public Matrix4x4[] Bindposes;
    }

    private DecodedMeshData _decodedMesh;

    /// <summary>
    /// Decodes the quantized mesh into engine-ready arrays and caches the result. Pure managed
    /// math — callable from a worker thread (the far avatar parse task does) as long as no
    /// other thread touches this payload concurrently; the cached copy is then reused by
    /// <see cref="CreateMesh"/> on the main thread.
    /// </summary>
    public DecodedMeshData PrepareDecodedMeshData()
    {
        if (_decodedMesh != null)
        {
            return _decodedMesh;
        }

        int vertexCount = VertexCount;
        DecodedMeshData decoded = new DecodedMeshData
        {
            Vertices = new Vector3[vertexCount],
            Normals = new Vector3[vertexCount],
            Uv = new Vector2[vertexCount],
            Triangles = new int[Indices.Length],
            BonesPerVertex = new byte[vertexCount],
        };
        for (int i = 0; i < vertexCount; i++)
        {
            decoded.Vertices[i] = DequantizePosition(i);
            decoded.Normals[i] = OctDecodeNormal(NormalsOct[i]);
            decoded.Uv[i] = DequantizeUv(i);
        }
        for (int i = 0; i < decoded.Triangles.Length; i++)
        {
            decoded.Triangles[i] = Indices[i];
        }

        int influenceCount = 0;
        for (int i = 0; i < vertexCount; i++)
        {
            influenceCount += BoneIndexB[i] != BoneIndexA[i] && BoneWeightA[i] < 255 ? 2 : 1;
        }
        decoded.BoneWeights = new BoneWeight1[influenceCount];
        int cursor = 0;
        for (int i = 0; i < vertexCount; i++)
        {
            float weightA = BoneWeightA[i] * (1f / 255f);
            bool twoInfluences = BoneIndexB[i] != BoneIndexA[i] && BoneWeightA[i] < 255;
            decoded.BonesPerVertex[i] = (byte)(twoInfluences ? 2 : 1);
            if (twoInfluences)
            {
                decoded.BoneWeights[cursor++] = new BoneWeight1 { boneIndex = BoneIndexA[i], weight = weightA };
                decoded.BoneWeights[cursor++] = new BoneWeight1 { boneIndex = BoneIndexB[i], weight = 1f - weightA };
            }
            else
            {
                decoded.BoneWeights[cursor++] = new BoneWeight1 { boneIndex = BoneIndexA[i], weight = 1f };
            }
        }

        ComputeBoneRootSpace(out Vector3[] bonePositions, out Quaternion[] boneRotations);
        decoded.Bindposes = new Matrix4x4[BoneCount];
        for (int i = 0; i < BoneCount; i++)
        {
            decoded.Bindposes[i] = InverseRigidTRS(bonePositions[i], boneRotations[i]);
        }

        _decodedMesh = decoded;
        return decoded;
    }

    /// <summary>
    /// Inverse of a rigid TRS (unit scale) without the native Matrix4x4.TRS/.inverse calls:
    /// R⁻¹ from the conjugate quaternion, translation −(R⁻¹·p). Exact for the unit rotations
    /// stored in the payload, and safe on worker threads.
    /// </summary>
    public static Matrix4x4 InverseRigidTRS(Vector3 position, Quaternion rotation)
    {
        float x = -rotation.x, y = -rotation.y, z = -rotation.z, w = rotation.w;
        float x2 = x + x, y2 = y + y, z2 = z + z;
        float xx = x * x2, yy = y * y2, zz = z * z2;
        float xy = x * y2, xz = x * z2, yz = y * z2;
        float wx = w * x2, wy = w * y2, wz = w * z2;

        Matrix4x4 m = default;
        m.m00 = 1f - (yy + zz); m.m01 = xy - wz; m.m02 = xz + wy;
        m.m10 = xy + wz; m.m11 = 1f - (xx + zz); m.m12 = yz - wx;
        m.m20 = xz - wy; m.m21 = yz + wx; m.m22 = 1f - (xx + yy);
        m.m03 = -(m.m00 * position.x + m.m01 * position.y + m.m02 * position.z);
        m.m13 = -(m.m10 * position.x + m.m11 * position.y + m.m12 * position.z);
        m.m23 = -(m.m20 * position.x + m.m21 * position.y + m.m22 * position.z);
        m.m33 = 1f;
        return m;
    }

    /// <summary>
    /// Drops the mesh/texture source data — quantized arrays, decoded cache, compressed
    /// texture bytes — once the shared Mesh/Texture2D exist. The skeleton, anchors and
    /// bounds stay (per-player skeleton builds read them). CreateMesh/CreateTexture and
    /// Serialize are invalid after this; only the runtime builder calls it.
    /// </summary>
    public void ReleaseMeshSourceData()
    {
        PositionsQ = null;
        NormalsOct = null;
        UvQ = null;
        BoneIndexA = null;
        BoneIndexB = null;
        BoneWeightA = null;
        Indices = null;
        Textures = Array.Empty<FarLodTexture>();
        _decodedMesh = null;
    }

    /// <summary>
    /// Builds the skinned far avatar mesh from this payload — the single construction path shared
    /// by the runtime far avatar and the SDK tester. Returns null (with a log) on bad data.
    /// The decode reuses <see cref="PrepareDecodedMeshData"/> when a worker thread already ran it.
    /// </summary>
    public Mesh CreateMesh()
    {
        try
        {
            DecodedMeshData decoded = PrepareDecodedMeshData();

            Mesh mesh = new Mesh { name = "BasisFarLodMesh" };
            mesh.vertices = decoded.Vertices;
            mesh.normals = decoded.Normals;
            mesh.uv = decoded.Uv;
            mesh.triangles = decoded.Triangles;

            using (NativeArray<byte> bonesPerVertex = new NativeArray<byte>(decoded.BonesPerVertex, Allocator.Temp))
            using (NativeArray<BoneWeight1> weights = new NativeArray<BoneWeight1>(decoded.BoneWeights, Allocator.Temp))
            {
                mesh.SetBoneWeights(bonesPerVertex, weights);
            }

            mesh.bindposes = decoded.Bindposes;
            mesh.bounds = new Bounds(
                (PositionBoundsMin + PositionBoundsMax) * 0.5f,
                PositionBoundsMax - PositionBoundsMin);
            mesh.UploadMeshData(true);
            return mesh;
        }
        catch (Exception e)
        {
            BasisDebug.LogError($"Far avatar mesh rejected: {e.Message}", BasisDebug.LogTag.Avatar);
            return null;
        }
    }

    /// <summary>
    /// Mipmap limit group for decoded far avatar atlases. Script-created textures can't join the
    /// mip STREAMING system (asset-pipeline textures only), but through this group they respect
    /// the global texture quality / mipmap limit — dropping the graphics tier sheds their top
    /// mips like any imported texture.
    /// </summary>
    public const string MipmapLimitGroup = "BasisAvatarFarLod";

    /// <summary>
    /// Builds the atlas texture from the first payload whose compression format this device
    /// supports. Returns null when none apply.
    /// </summary>
    public Texture2D CreateTexture()
    {
        for (int i = 0; i < Textures.Length; i++)
        {
            FarLodTexture texturePayload = Textures[i];
            TextureFormat format;
            switch (texturePayload.Format)
            {
                case FarLodTextureFormat.BC1: format = TextureFormat.DXT1; break;
                case FarLodTextureFormat.ASTC6x6: format = TextureFormat.ASTC_6x6; break;
                case FarLodTextureFormat.RGBA32: format = TextureFormat.RGBA32; break;
                default: continue;
            }
            if (!SystemInfo.SupportsTextureFormat(format))
            {
                continue;
            }
            // Mipmap-limit participation is best-effort: with an active nonzero limit Unity
            // allocates a trimmed chain and full-chain LoadRawTextureData throws. Never let
            // that cost us the texture — fall back to plain construction.
            Texture2D texture = null;
            try
            {
                texture = CreateTextureForPayload(texturePayload, format, useMipmapLimit: true);
            }
            catch (Exception e)
            {
                BasisDebug.Log($"Far avatar atlas mip-limit path unavailable ({e.Message}) — using plain texture.", BasisDebug.LogTag.Avatar);
                texture = null;
            }
            if (texture == null)
            {
                try
                {
                    texture = CreateTextureForPayload(texturePayload, format, useMipmapLimit: false);
                }
                catch (Exception e)
                {
                    BasisDebug.LogError($"Far avatar texture rejected: {e.Message}", BasisDebug.LogTag.Avatar);
                }
            }
            if (texture != null)
            {
                return texture;
            }
        }
        return null;
    }

    private static Texture2D CreateTextureForPayload(in FarLodTexture texturePayload, TextureFormat format, bool useMipmapLimit)
    {
        bool hasMips = texturePayload.MipCount > 1;
        Texture2D texture;
        if (useMipmapLimit && hasMips)
        {
            // Limit groups can only be authored in Quality Settings (no runtime creation in
            // this Unity version) — use ours when someone has added it there, otherwise
            // participate through the global texture mipmap limit.
            string limitGroup = TextureMipmapLimitGroups.HasGroup(MipmapLimitGroup) ? MipmapLimitGroup : string.Empty;
            texture = new Texture2D(texturePayload.Width, texturePayload.Height, format,
                texturePayload.MipCount, false, false, new MipmapLimitDescriptor(true, limitGroup));
        }
        else
        {
            texture = new Texture2D(texturePayload.Width, texturePayload.Height, format, hasMips, false);
        }
        texture.name = "BasisFarLodAtlas";
        texture.wrapMode = TextureWrapMode.Clamp;
        texture.filterMode = FilterMode.Trilinear;
        texture.anisoLevel = 1;
        try
        {
            texture.LoadRawTextureData(texturePayload.Data);
            texture.Apply(false, true);
        }
        catch
        {
            if (Application.isPlaying)
            {
                UnityEngine.Object.Destroy(texture);
            }
            else
            {
                UnityEngine.Object.DestroyImmediate(texture);
            }
            throw;
        }
        return texture;
    }

    public Vector3 DequantizePosition(int vertexIndex)
    {
        Vector3 range = PositionBoundsMax - PositionBoundsMin;
        int baseIndex = vertexIndex * 3;
        return new Vector3(
            PositionBoundsMin.x + range.x * (PositionsQ[baseIndex] * (1f / 65535f)),
            PositionBoundsMin.y + range.y * (PositionsQ[baseIndex + 1] * (1f / 65535f)),
            PositionBoundsMin.z + range.z * (PositionsQ[baseIndex + 2] * (1f / 65535f)));
    }

    public Vector2 DequantizeUv(int vertexIndex)
    {
        return new Vector2(UvQ[vertexIndex * 2] * (1f / 65535f), UvQ[vertexIndex * 2 + 1] * (1f / 65535f));
    }

    public static ushort QuantizeUnorm(float value)
    {
        return (ushort)Mathf.Clamp(Mathf.RoundToInt(Mathf.Clamp01(value) * 65535f), 0, 65535);
    }

    public static ushort OctEncodeNormal(Vector3 normal)
    {
        float sum = Mathf.Abs(normal.x) + Mathf.Abs(normal.y) + Mathf.Abs(normal.z);
        if (sum < 1e-8f)
        {
            normal = Vector3.up;
            sum = 1f;
        }
        float x = normal.x / sum;
        float y = normal.y / sum;
        if (normal.z < 0f)
        {
            float ox = x;
            x = (1f - Mathf.Abs(y)) * (ox >= 0f ? 1f : -1f);
            y = (1f - Mathf.Abs(ox)) * (y >= 0f ? 1f : -1f);
        }
        int ux = Mathf.Clamp(Mathf.RoundToInt((x * 0.5f + 0.5f) * 255f), 0, 255);
        int uy = Mathf.Clamp(Mathf.RoundToInt((y * 0.5f + 0.5f) * 255f), 0, 255);
        return (ushort)(ux | (uy << 8));
    }

    public static Vector3 OctDecodeNormal(ushort encoded)
    {
        float x = ((encoded & 0xFF) * (1f / 255f)) * 2f - 1f;
        float y = (((encoded >> 8) & 0xFF) * (1f / 255f)) * 2f - 1f;
        float z = 1f - Mathf.Abs(x) - Mathf.Abs(y);
        if (z < 0f)
        {
            float ox = x;
            x = (1f - Mathf.Abs(y)) * (ox >= 0f ? 1f : -1f);
            y = (1f - Mathf.Abs(ox)) * (y >= 0f ? 1f : -1f);
        }
        return new Vector3(x, y, z).normalized;
    }

    private static void WriteVector2(BinaryWriter writer, Vector2 value)
    {
        writer.Write(value.x);
        writer.Write(value.y);
    }

    private static void WriteVector3(BinaryWriter writer, Vector3 value)
    {
        writer.Write(value.x);
        writer.Write(value.y);
        writer.Write(value.z);
    }

    private static void WriteQuaternion(BinaryWriter writer, Quaternion value)
    {
        writer.Write(value.x);
        writer.Write(value.y);
        writer.Write(value.z);
        writer.Write(value.w);
    }

    private static Vector2 ReadVector2(BinaryReader reader)
    {
        return new Vector2(reader.ReadSingle(), reader.ReadSingle());
    }

    private static Vector3 ReadVector3(BinaryReader reader)
    {
        return new Vector3(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
    }

    private static Quaternion ReadQuaternion(BinaryReader reader)
    {
        return new Quaternion(reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle(), reader.ReadSingle());
    }

    private static ushort[] ReadUInt16Array(BinaryReader reader, int count)
    {
        ushort[] values = new ushort[count];
        for (int i = 0; i < count; i++)
        {
            values[i] = reader.ReadUInt16();
        }
        return values;
    }
}
