#!/usr/bin/env bash
set -euo pipefail

# Renders /etc/caddy/Caddyfile from the domains in .env.local and reloads
# Caddy. Caddy terminates TLS for Concierge and the WebGL client and obtains
# the certificate that GameServers use for wss (see tools/caddy-sync-cert.sh).

repository_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=tools/public-env.sh
source "${repository_root}/tools/public-env.sh"

caddyfile_path="${CADDYFILE_PATH:-/etc/caddy/Caddyfile}"
admin_allow_ips="${CADDY_ADMIN_ALLOW_IPS:-}"
acme_email="${CADDY_ACME_EMAIL:-}"

if ! command -v caddy >/dev/null 2>&1; then
  echo "caddy is required; run mise install first." >&2
  exit 1
fi

render_caddyfile() {
  if [[ -n "$acme_email" ]]; then
    cat <<EOF
{
	email ${acme_email}
}

EOF
  fi

  cat <<EOF
# Generated by tools/caddy-apply.sh. Edit .env.local and re-run that script
# instead of changing this file by hand.

${concierge_domain} {
EOF
  if [[ -n "$admin_allow_ips" ]]; then
    cat <<EOF
	@admin path /admin*
	@admin_allowed {
		path /admin*
		remote_ip ${admin_allow_ips//,/ }
	}
	handle @admin_allowed {
		reverse_proxy 127.0.0.1:${concierge_node_port}
	}
	handle @admin {
		respond "Forbidden" 403
	}
	handle {
		reverse_proxy 127.0.0.1:${concierge_node_port}
	}
EOF
  else
    cat <<EOF
	reverse_proxy 127.0.0.1:${concierge_node_port}
EOF
  fi
  cat <<EOF
}

${web_domain} {
	reverse_proxy 127.0.0.1:${web_node_port}
}

# Rooms are served by the Agones GameServers themselves on dynamic ports, so
# this site exists only to obtain and renew the certificate that
# tools/caddy-sync-cert.sh copies into the basis-web-tls Secret.
${rooms_domain} {
	respond 204
}
EOF
}

work_dir="$(mktemp -d)"
cleanup_work_dir() {
  rm -rf -- "$work_dir"
}
trap cleanup_work_dir EXIT

render_caddyfile > "$work_dir/Caddyfile"
caddy validate --adapter caddyfile --config "$work_dir/Caddyfile"
sudo mkdir -p "$(dirname "$caddyfile_path")"
sudo install -m 644 "$work_dir/Caddyfile" "$caddyfile_path"

if systemctl is-active --quiet caddy; then
  sudo systemctl reload caddy
else
  sudo systemctl enable --now caddy
fi

echo "Applied $caddyfile_path"
echo "Sites: https://${concierge_domain}, https://${web_domain}, https://${rooms_domain}"
if [[ -z "$admin_allow_ips" ]]; then
  echo "Admin API is reachable from anywhere; set CADDY_ADMIN_ALLOW_IPS in .env.local to restrict it." >&2
fi
echo "Certificates are issued once 80/tcp and 443/tcp reach this host and DNS points at it."
