//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

// AccessConfig defines model for AccessConfig.
type AccessConfig struct {
	AllowedClaims *[]ClaimRule `json:"allowedClaims,omitempty"`
	AllowedGroups *[]string    `json:"allowedGroups,omitempty"`
}

// AdminServerInfo defines model for AdminServerInfo.
type AdminServerInfo struct {
	HasTicketSigningKey                   bool              `json:"hasTicketSigningKey"`
	HasTransportPublicKey                 bool              `json:"hasTransportPublicKey"`
	Id                                    string            `json:"id"`
	Providers                             []ProviderOptions `json:"providers"`
	Ready                                 bool              `json:"ready"`
	TicketSigningKeyEnvironmentVariable   *string           `json:"ticketSigningKeyEnvironmentVariable,omitempty"`
	TransportPublicKeyEnvironmentVariable *string           `json:"transportPublicKeyEnvironmentVariable,omitempty"`
}

// AdminServerWrite Body for PUT /admin/servers/{serverId} (BrokerServerOptions equivalent).
type AdminServerWrite struct {
	Id                                    *string            `json:"id,omitempty"`
	Providers                             *[]ProviderOptions `json:"providers,omitempty"`
	TicketSigningKey                      *string            `json:"ticketSigningKey,omitempty"`
	TicketSigningKeyEnvironmentVariable   *string            `json:"ticketSigningKeyEnvironmentVariable,omitempty"`
	TransportPublicKey                    *string            `json:"transportPublicKey,omitempty"`
	TransportPublicKeyEnvironmentVariable *string            `json:"transportPublicKeyEnvironmentVariable,omitempty"`
}

// AdmissionRequest defines model for AdmissionRequest.
type AdmissionRequest struct {
	Did     string `json:"did"`
	IdToken string `json:"idToken"`
}

// AdmissionResponse defines model for AdmissionResponse.
type AdmissionResponse struct {
	Ticket string `json:"ticket"`
}

// ClaimRule defines model for ClaimRule.
type ClaimRule struct {
	Claim  *string   `json:"claim,omitempty"`
	Values *[]string `json:"values,omitempty"`
}

// ClientConfiguration defines model for ClientConfiguration.
type ClientConfiguration struct {
	DefaultProviderId *string                 `json:"defaultProviderId,omitempty"`
	Enforcement       *EnforcementConfig      `json:"enforcement,omitempty"`
	Providers         *[]ClientProviderConfig `json:"providers,omitempty"`
	Redirect          *RedirectConfig         `json:"redirect,omitempty"`
	ServerTransport   *ServerTransportConfig  `json:"serverTransport,omitempty"`
}

// ClientProviderConfig defines model for ClientProviderConfig.
type ClientProviderConfig struct {
	Access            *AccessConfig `json:"access,omitempty"`
	ClientId          *string       `json:"clientId,omitempty"`
	ClientSecret      *string       `json:"clientSecret,omitempty"`
	DisplayNameClaims *[]string     `json:"displayNameClaims,omitempty"`
	Id                *string       `json:"id,omitempty"`
	Issuer            *string       `json:"issuer,omitempty"`
	Label             *string       `json:"label,omitempty"`
	Scopes            *[]string     `json:"scopes,omitempty"`
}

// CreateMeetingRequest defines model for CreateMeetingRequest.
type CreateMeetingRequest struct {
	Host     *string `json:"host,omitempty"`
	Id       *string `json:"id,omitempty"`
	Password *string `json:"password,omitempty"`
	Port     *int    `json:"port,omitempty"`
	Title    string  `json:"title"`
}

// EnforcementConfig defines model for EnforcementConfig.
type EnforcementConfig struct {
	AllowOfflineWithinTokenValidity *bool `json:"allowOfflineWithinTokenValidity,omitempty"`
}

// EnrollmentResponse defines model for EnrollmentResponse.
type EnrollmentResponse struct {
	ExpiresInSeconds int    `json:"expiresInSeconds"`
	Url              string `json:"url"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Error   *string            `json:"error,omitempty"`
	Servers []HealthServerInfo `json:"servers"`
	Status  string             `json:"status"`
}

// HealthServerInfo defines model for HealthServerInfo.
type HealthServerInfo struct {
	Id        string   `json:"id"`
	Providers []string `json:"providers"`
	Ready     bool     `json:"ready"`
}

// InvitationResponse defines model for InvitationResponse.
type InvitationResponse struct {
	MeetingId string `json:"meetingId"`
	Url       string `json:"url"`
}

// JoinManifest defines model for JoinManifest.
type JoinManifest struct {
	Connection      *JoinManifestConnection `json:"connection,omitempty"`
	Meeting         *JoinManifestMeeting    `json:"meeting,omitempty"`
	ServerTransport *ServerTransportConfig  `json:"serverTransport,omitempty"`
}

// JoinManifestConnection defines model for JoinManifestConnection.
type JoinManifestConnection struct {
	Host     *string `json:"host,omitempty"`
	Password *string `json:"password,omitempty"`
	Port     *int    `json:"port,omitempty"`
}

// JoinManifestMeeting defines model for JoinManifestMeeting.
type JoinManifestMeeting struct {
	Id    *string `json:"id,omitempty"`
	Title *string `json:"title,omitempty"`
}

// MeetingView defines model for MeetingView.
type MeetingView struct {
	CreatedAt       time.Time `json:"createdAt"`
	Host            string    `json:"host"`
	Id              string    `json:"id"`
	InvitationReady bool      `json:"invitationReady"`
	JoinUrl         string    `json:"joinUrl"`
	Port            int       `json:"port"`
	Status          string    `json:"status"`
	StatusDetail    string    `json:"statusDetail"`
	Title           string    `json:"title"`
	UpdatedAt       time.Time `json:"updatedAt"`
}

// OrganizationOptions defines model for OrganizationOptions.
type OrganizationOptions struct {
	DefaultProviderId *string            `json:"defaultProviderId,omitempty"`
	DisplayName       *string            `json:"displayName,omitempty"`
	Providers         *[]ProviderOptions `json:"providers,omitempty"`
}

// ProblemDetails RFC 7807 application/problem+json envelope, matching ASP.NET Core's Results.Problem default shape.
type ProblemDetails struct {
	Detail *string `json:"detail,omitempty"`
	Status *int    `json:"status,omitempty"`
	Title  *string `json:"title,omitempty"`
	Type   *string `json:"type,omitempty"`
}

// ProviderOptions defines model for ProviderOptions.
type ProviderOptions struct {
	AllowedGroups        *[]string `json:"allowedGroups,omitempty"`
	AllowedHostedDomains *[]string `json:"allowedHostedDomains,omitempty"`
	Audience             *string   `json:"audience,omitempty"`
	ClientSecret         *string   `json:"clientSecret,omitempty"`
	Id                   *string   `json:"id,omitempty"`
	Issuer               *string   `json:"issuer,omitempty"`
	JwksUri              *string   `json:"jwksUri,omitempty"`
	Label                *string   `json:"label,omitempty"`
}

// RedirectConfig defines model for RedirectConfig.
type RedirectConfig struct {
	Host *string `json:"host,omitempty"`
	Mode *string `json:"mode,omitempty"`
	Path *string `json:"path,omitempty"`
	Port *int    `json:"port,omitempty"`
}

// ServerTransportConfig defines model for ServerTransportConfig.
type ServerTransportConfig struct {
	AdmissionEndpoint                 *string `json:"admissionEndpoint,omitempty"`
	AllowUntrustedLoopbackCertificate *bool   `json:"allowUntrustedLoopbackCertificate,omitempty"`
	ServerPublicKey                   *string `json:"serverPublicKey,omitempty"`
}

// MeetingId defines model for MeetingId.
type MeetingId = string

// ServerId defines model for ServerId.
type ServerId = string

// Token defines model for Token.
type Token = string

// PutAdminClientConfigJSONBody defines parameters for PutAdminClientConfig.
type PutAdminClientConfigJSONBody = map[string]interface{}

// PutAdminClientConfigJSONRequestBody defines body for PutAdminClientConfig for application/json ContentType.
type PutAdminClientConfigJSONRequestBody = PutAdminClientConfigJSONBody

// CreateMeetingJSONRequestBody defines body for CreateMeeting for application/json ContentType.
type CreateMeetingJSONRequestBody = CreateMeetingRequest

// PutOrganizationJSONRequestBody defines body for PutOrganization for application/json ContentType.
type PutOrganizationJSONRequestBody = OrganizationOptions

// PutAdminServerJSONRequestBody defines body for PutAdminServer for application/json ContentType.
type PutAdminServerJSONRequestBody = AdminServerWrite

// AdmitJSONRequestBody defines body for Admit for application/json ContentType.
type AdmitJSONRequestBody = AdmissionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /admin/client-config-template/{serverId})
	GetClientConfigTemplate(w http.ResponseWriter, r *http.Request, serverId ServerId)

	// (GET /admin/client-config/{serverId})
	GetAdminClientConfig(w http.ResponseWriter, r *http.Request, serverId ServerId)

	// (PUT /admin/client-config/{serverId})
	PutAdminClientConfig(w http.ResponseWriter, r *http.Request, serverId ServerId)

	// (POST /admin/enrollment/{serverId})
	CreateEnrollment(w http.ResponseWriter, r *http.Request, serverId ServerId)

	// (GET /admin/meetings)
	ListMeetings(w http.ResponseWriter, r *http.Request)

	// (POST /admin/meetings)
	CreateMeeting(w http.ResponseWriter, r *http.Request)

	// (DELETE /admin/meetings/{meetingId})
	DeleteMeeting(w http.ResponseWriter, r *http.Request, meetingId MeetingId)

	// (POST /admin/meetings/{meetingId}/invitations)
	CreateInvitation(w http.ResponseWriter, r *http.Request, meetingId MeetingId)

	// (GET /admin/organization)
	GetOrganization(w http.ResponseWriter, r *http.Request)

	// (PUT /admin/organization)
	PutOrganization(w http.ResponseWriter, r *http.Request)

	// (GET /admin/servers)
	ListAdminServers(w http.ResponseWriter, r *http.Request)

	// (DELETE /admin/servers/{serverId})
	DeleteAdminServer(w http.ResponseWriter, r *http.Request, serverId ServerId)

	// (PUT /admin/servers/{serverId})
	PutAdminServer(w http.ResponseWriter, r *http.Request, serverId ServerId)

	// (POST /admission/{serverId})
	Admit(w http.ResponseWriter, r *http.Request, serverId ServerId)

	// (GET /client-config/{serverId})
	GetClientConfig(w http.ResponseWriter, r *http.Request, serverId ServerId)

	// (GET /enroll/{token})
	EnrollLanding(w http.ResponseWriter, r *http.Request, token Token)

	// (GET /enroll/{token}/config)
	EnrollConfig(w http.ResponseWriter, r *http.Request, token Token)

	// (GET /health)
	Health(w http.ResponseWriter, r *http.Request)

	// (GET /join/{token})
	JoinPage(w http.ResponseWriter, r *http.Request, token Token)

	// (GET /join/{token}/config)
	JoinConfig(w http.ResponseWriter, r *http.Request, token Token)

	// (GET /join/{token}/manifest)
	JoinManifest(w http.ResponseWriter, r *http.Request, token Token)

	// (GET /join/{token}/open)
	JoinOpenPage(w http.ResponseWriter, r *http.Request, token Token)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetClientConfigTemplate operation middleware
func (siw *ServerInterfaceWrapper) GetClientConfigTemplate(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "serverId" -------------
	var serverId ServerId

	err = runtime.BindStyledParameterWithOptions("simple", "serverId", r.PathValue("serverId"), &serverId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serverId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetClientConfigTemplate(w, r, serverId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminClientConfig operation middleware
func (siw *ServerInterfaceWrapper) GetAdminClientConfig(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "serverId" -------------
	var serverId ServerId

	err = runtime.BindStyledParameterWithOptions("simple", "serverId", r.PathValue("serverId"), &serverId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serverId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminClientConfig(w, r, serverId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutAdminClientConfig operation middleware
func (siw *ServerInterfaceWrapper) PutAdminClientConfig(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "serverId" -------------
	var serverId ServerId

	err = runtime.BindStyledParameterWithOptions("simple", "serverId", r.PathValue("serverId"), &serverId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serverId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutAdminClientConfig(w, r, serverId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateEnrollment operation middleware
func (siw *ServerInterfaceWrapper) CreateEnrollment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "serverId" -------------
	var serverId ServerId

	err = runtime.BindStyledParameterWithOptions("simple", "serverId", r.PathValue("serverId"), &serverId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serverId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateEnrollment(w, r, serverId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMeetings operation middleware
func (siw *ServerInterfaceWrapper) ListMeetings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMeetings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateMeeting operation middleware
func (siw *ServerInterfaceWrapper) CreateMeeting(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateMeeting(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteMeeting operation middleware
func (siw *ServerInterfaceWrapper) DeleteMeeting(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "meetingId" -------------
	var meetingId MeetingId

	err = runtime.BindStyledParameterWithOptions("simple", "meetingId", r.PathValue("meetingId"), &meetingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "meetingId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMeeting(w, r, meetingId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateInvitation operation middleware
func (siw *ServerInterfaceWrapper) CreateInvitation(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "meetingId" -------------
	var meetingId MeetingId

	err = runtime.BindStyledParameterWithOptions("simple", "meetingId", r.PathValue("meetingId"), &meetingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "meetingId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateInvitation(w, r, meetingId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOrganization operation middleware
func (siw *ServerInterfaceWrapper) GetOrganization(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOrganization(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutOrganization operation middleware
func (siw *ServerInterfaceWrapper) PutOrganization(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutOrganization(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAdminServers operation middleware
func (siw *ServerInterfaceWrapper) ListAdminServers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAdminServers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAdminServer operation middleware
func (siw *ServerInterfaceWrapper) DeleteAdminServer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "serverId" -------------
	var serverId ServerId

	err = runtime.BindStyledParameterWithOptions("simple", "serverId", r.PathValue("serverId"), &serverId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serverId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAdminServer(w, r, serverId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutAdminServer operation middleware
func (siw *ServerInterfaceWrapper) PutAdminServer(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "serverId" -------------
	var serverId ServerId

	err = runtime.BindStyledParameterWithOptions("simple", "serverId", r.PathValue("serverId"), &serverId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serverId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutAdminServer(w, r, serverId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Admit operation middleware
func (siw *ServerInterfaceWrapper) Admit(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "serverId" -------------
	var serverId ServerId

	err = runtime.BindStyledParameterWithOptions("simple", "serverId", r.PathValue("serverId"), &serverId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serverId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Admit(w, r, serverId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetClientConfig operation middleware
func (siw *ServerInterfaceWrapper) GetClientConfig(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "serverId" -------------
	var serverId ServerId

	err = runtime.BindStyledParameterWithOptions("simple", "serverId", r.PathValue("serverId"), &serverId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serverId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetClientConfig(w, r, serverId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EnrollLanding operation middleware
func (siw *ServerInterfaceWrapper) EnrollLanding(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "token" -------------
	var token Token

	err = runtime.BindStyledParameterWithOptions("simple", "token", r.PathValue("token"), &token, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EnrollLanding(w, r, token)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// EnrollConfig operation middleware
func (siw *ServerInterfaceWrapper) EnrollConfig(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "token" -------------
	var token Token

	err = runtime.BindStyledParameterWithOptions("simple", "token", r.PathValue("token"), &token, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.EnrollConfig(w, r, token)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Health(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// JoinPage operation middleware
func (siw *ServerInterfaceWrapper) JoinPage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "token" -------------
	var token Token

	err = runtime.BindStyledParameterWithOptions("simple", "token", r.PathValue("token"), &token, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.JoinPage(w, r, token)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// JoinConfig operation middleware
func (siw *ServerInterfaceWrapper) JoinConfig(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "token" -------------
	var token Token

	err = runtime.BindStyledParameterWithOptions("simple", "token", r.PathValue("token"), &token, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.JoinConfig(w, r, token)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// JoinManifest operation middleware
func (siw *ServerInterfaceWrapper) JoinManifest(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "token" -------------
	var token Token

	err = runtime.BindStyledParameterWithOptions("simple", "token", r.PathValue("token"), &token, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.JoinManifest(w, r, token)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// JoinOpenPage operation middleware
func (siw *ServerInterfaceWrapper) JoinOpenPage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "token" -------------
	var token Token

	err = runtime.BindStyledParameterWithOptions("simple", "token", r.PathValue("token"), &token, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "token", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.JoinOpenPage(w, r, token)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/client-config/{serverId}", wrapper.GetClientConfig)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.Health)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/admission/{serverId}", wrapper.Admit)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/enroll/{token}", wrapper.EnrollLanding)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/enroll/{token}/config", wrapper.EnrollConfig)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/join/{token}/config", wrapper.JoinConfig)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/join/{token}", wrapper.JoinPage)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/join/{token}/open", wrapper.JoinOpenPage)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/join/{token}/manifest", wrapper.JoinManifest)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/admin/servers", wrapper.ListAdminServers)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/admin/organization", wrapper.GetOrganization)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/admin/organization", wrapper.PutOrganization)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/admin/meetings", wrapper.ListMeetings)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/admin/meetings", wrapper.CreateMeeting)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/admin/meetings/{meetingId}", wrapper.DeleteMeeting)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/admin/meetings/{meetingId}/invitations", wrapper.CreateInvitation)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/admin/servers/{serverId}", wrapper.DeleteAdminServer)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/admin/servers/{serverId}", wrapper.PutAdminServer)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/admin/client-config-template/{serverId}", wrapper.GetClientConfigTemplate)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/admin/client-config/{serverId}", wrapper.GetAdminClientConfig)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/admin/client-config/{serverId}", wrapper.PutAdminClientConfig)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/admin/enrollment/{serverId}", wrapper.CreateEnrollment)

	return m
}
